### PR TITLE
Updates variables to be double letters and expose asteroid class size to global variable

### PR DESCRIPTION
**Pull request by th3fallen**
Also exposes the asteroid class number as a variable for automated laser alignment purposes

New Variables Names are:
Active: AC
Index: IN
ScanResults: SR
Material: MA
Volume: VO
Scan: SC
Reset: RE

Asteroid Class: SZ

This prevents conflicts with ISAN

### CODE REVIEW

**Review by abiosbug — COMMENTED** [review]
This PR attempts to solve the exact same issue as #4  The new variable names are now `AC IN SR SC MA` and are imo more likely to be overseen in complex setups.  Instead of creating a new PR, consider adding to the existing one via the discussion if you would have done something different, I'll be more than happy to incorporate improvements.

**Comment by abiosbug** [comment]
The  SCC edition version needs adjusting too, but there's also https://github.com/DerPfandadler/Pfandadler-YOLOL/pull/4#issuecomment-919918438

**Comment by th3fallen** [comment]
> The SCC edition version needs adjusting too, but there's also [#4 (comment)](https://github.com/DerPfandadler/Pfandadler-YOLOL/pull/4#issuecomment-919918438)

That's why I didn't update it. Just offering an alternative not trying to compete.

**Comment by abiosbug** [comment]
No need to make this personal @th3fallen, but since we're here now: what I usually do if I end up creating a PR that solves an issue that is already being solved by an existing PR, is to add my new findings (if any) to the existing one and close mine as duplicate.

Edit: Editing out your assumption that I was angry doesn't change a thing.

**Comment by th3fallen** [comment]
> No need to make this personal @th3fallen, but since we're here now: what I usually do if I end up creating a PR that solves an issue that is already being solved by an existing PR, is to add my new findings (if any) to the existing one and close mine as duplicate.

there was nothing personal in my previous response. but since your comments are now bordering on harassment I'll kindly ask you to refrain from polluting this PR with pointless comments.

**Comment by DerPfandadler** [comment]
I will expose the asteroid class as a global variable and adjust device field names.

**Pull request closed without merging**
